/**
 * 初始化示例数据。
 * 启动时或手动执行 node seed.js 时调用，整个过程在事务中完成。
 */
const db = require('./store/db');
const { hashPassword } = require('./utils/password');

// 整个初始化过程使用事务，避免只写入部分数据。
const runSeed = db._db.transaction(() => {
  // 用户。
  db.seed('users', [
    {
      id: 'u001',
      username: 'o',
      password: hashPassword('123'),
      avatar: null,
      role: 'owner',
    },
    {
      id: 'u002',
      username: 'a',
      password: hashPassword('123'),
      avatar: null,
      role: 'annotator',
    },
    {
      id: 'u003',
      username: 'r',
      password: hashPassword('123'),
      avatar: null,
      role: 'reviewer',
    },
  ]);

  // 任务。
  db.seed('tasks', [
    {
      id: 't001',
      name: '猫狗图像分类-批次A',
      description: '对猫狗图片进行二分类标注，区分猫与狗的图像。',
      type: 'image_classification',
      owner: 'o',
      templateId: 'tpl001',
      templateName: '图像分类模板v1',
      instructions: '请根据图片内容选择"猫"或"狗"标签，不确定的标记为"不确定"。',
      status: 'in_progress',
      createdAt: '2026-04-12T10:30:00Z',
    },
    {
      id: 't002',
      name: '交通标志检测-批次B',
      description: '标注交通场景中的各类标志牌位置。',
      type: 'object_detection',
      owner: 'o',
      templateId: 'tpl004',
      templateName: '目标检测模板v2',
      instructions: '用矩形框标注所有交通标志，类别从下拉列表中选择。',
      status: 'draft',
      createdAt: '2026-04-18T09:15:00Z',
    },
    {
      id: 't003',
      name: '遥感图像语义分割',
      description: '对遥感卫星图像进行地物语义分割。',
      type: 'semantic_segmentation',
      owner: 'o',
      templateId: 'tpl005',
      templateName: '语义分割模板v1',
      instructions: '使用多边形工具勾勒地物边界，分类包括：建筑、植被、水体、道路。',
      status: 'pending',
      createdAt: '2026-04-20T14:00:00Z',
    },
    {
      id: 't004',
      name: '医疗报告实体识别',
      description: '从医疗报告中识别疾病、药物等命名实体。',
      type: 'text_ner',
      owner: 'o',
      templateId: 'tpl007',
      templateName: 'NER模板v1',
      instructions: '标注文本中的疾病、药物、检查项目等实体，使用对应颜色高亮。',
      status: 'completed',
      createdAt: '2026-03-05T08:45:00Z',
      archived: true,
      archivedAt: '2026-04-01T10:00:00Z',
    },
    {
      id: 't005',
      name: '猫狗图像分类-批次B',
      description: '第二批猫狗图片的二分类标注。',
      type: 'image_classification',
      owner: 'o',
      templateId: 'tpl001',
      templateName: '图像分类模板v1',
      instructions: '标注规范与批次A相同。',
      status: 'ended',
      createdAt: '2026-02-10T16:20:00Z',
      archived: true,
      archivedAt: '2026-03-15T14:00:00Z',
    },
    {
      id: 't006',
      name: '行人与车辆检测',
      description: '检测街景图像中的行人与车辆。',
      type: 'object_detection',
      owner: 'o',
      templateId: 'tpl004',
      templateName: '目标检测模板v2',
      instructions: '分别用矩形框标注行人和车辆，确保不遗漏边缘目标。',
      status: 'in_progress',
      createdAt: '2026-04-25T11:30:00Z',
    },
    {
      id: 't007',
      name: '卫星图像地物分类',
      description: '对卫星图像进行地物像素级分类。',
      type: 'semantic_segmentation',
      owner: 'o',
      templateId: 'tpl006',
      templateName: '语义分割模板v2',
      instructions: '按像素级别标注地物类型，注意处理云遮挡区域。',
      status: 'draft',
      createdAt: '2026-05-01T09:00:00Z',
    },
    {
      id: 't008',
      name: '新闻文本命名实体识别',
      description: '对新闻文本进行人名、地名、机构名实体识别。',
      type: 'text_ner',
      owner: 'o',
      templateId: 'tpl008',
      templateName: 'NER模板v2',
      instructions: '标注人名、地名、机构名三类实体，重叠部分取最长匹配。',
      status: 'pending',
      createdAt: '2026-05-03T13:10:00Z',
    },
    {
      id: 't009',
      name: '农作物病害图像分类',
      description: '对农作物图片进行病害类型分类。',
      type: 'image_classification',
      owner: 'o',
      templateId: 'tpl002',
      templateName: '图像分类模板v2',
      instructions: '选择对应的病害类型标签，健康植株标注为"健康"。',
      status: 'in_progress',
      createdAt: '2026-05-08T07:30:00Z',
    },
    {
      id: 't010',
      name: '工业缺陷检测-批次C',
      description: '检测工业产品图像中的表面缺陷。',
      type: 'object_detection',
      owner: 'o',
      templateId: 'tpl003',
      templateName: '目标检测模板v1',
      instructions: '用矩形框标注缺陷区域，标注缺陷类型：划痕、凹陷、色差。',
      status: 'completed',
      createdAt: '2026-03-20T15:45:00Z',
      archived: true,
      archivedAt: '2026-04-10T09:30:00Z',
    },
    {
      id: 't011',
      name: '街景语义分割-批次A',
      description: '对街道场景图像进行语义分割。',
      type: 'semantic_segmentation',
      owner: 'o',
      templateId: 'tpl005',
      templateName: '语义分割模板v1',
      instructions: '标注道路、人行道、建筑、天空等区域。',
      status: 'ended',
      createdAt: '2026-01-15T10:00:00Z',
      archived: true,
      archivedAt: '2026-02-28T16:00:00Z',
    },
    {
      id: 't012',
      name: '电商评论NER',
      description: '对电商评论进行产品属性和情感实体识别。',
      type: 'text_ner',
      owner: 'o',
      templateId: 'tpl007',
      templateName: 'NER模板v1',
      instructions: '标注产品属性、情感倾向等实体，保持粒度一致。',
      status: 'draft',
      createdAt: '2026-05-10T17:00:00Z',
    },
  ]);

  // 模板及字段定义。
  db.seed('templates', [
    {
      id: 'tpl001',
      name: '图像分类模板v1',
      description: '适用于猫狗、农作物等图像分类场景，支持单选类别与附加标签。',
      type: 'image_classification',
      fieldCount: 8,
      creator: 'o',
      createdAt: '2026-03-10T09:00:00Z',
      fields: [
        {
          id: 'f_title_1',
          type: 'title',
          fieldKey: '',
          label: '标注须知',
          description: '请仔细阅读后进行标注，注意区分目标物体类别。',
          level: 4,
        },
        {
          id: 'f_category',
          type: 'radio',
          fieldKey: 'category',
          label: '图像类别',
          required: true,
          description: '选择图像中主要物体的类别',
          options: [
            { id: 'opt1', label: '猫', value: 'cat' },
            { id: 'opt2', label: '狗', value: 'dog' },
            { id: 'opt3', label: '鸟', value: 'bird' },
            { id: 'opt4', label: '其他', value: 'other' },
          ],
          direction: 'vertical',
        },
        {
          id: 'f_tags',
          type: 'checkbox',
          fieldKey: 'tags',
          label: '附加标签',
          options: [
            { id: 'opt5', label: '室内', value: 'indoor' },
            { id: 'opt6', label: '室外', value: 'outdoor' },
            { id: 'opt7', label: '近景', value: 'closeup' },
            { id: 'opt8', label: '远景', value: 'distant' },
          ],
          direction: 'horizontal',
          maxCheck: 2,
        },
        {
          id: 'f_quality',
          type: 'select',
          fieldKey: 'quality',
          label: '图像质量',
          required: true,
          placeholder: '请选择质量等级',
          options: [
            { id: 'opt9', label: '高清', value: 'hd' },
            { id: 'opt10', label: '标准', value: 'sd' },
            { id: 'opt11', label: '模糊', value: 'blurry' },
          ],
          searchable: true,
        },
        {
          id: 'f_difficulty',
          type: 'rating',
          fieldKey: 'difficulty',
          label: '标注难度',
          description: '1=简单 5=极难',
          maxScore: 5,
          allowHalf: true,
          defaultValue: 3,
        },
        {
          id: 'f_isclear',
          type: 'switch',
          fieldKey: 'isClear',
          label: '目标是否清晰',
          defaultValue: false,
          checkedChildren: '清晰',
          unCheckedChildren: '模糊',
        },
        {
          id: 'f_note',
          type: 'textarea',
          fieldKey: 'note',
          label: '备注',
          placeholder: '补充说明（可选）',
          maxLength: 500,
          autoSize: true,
        },
        {
          id: 'f_url',
          type: 'input',
          fieldKey: 'sourceUrl',
          label: '数据来源URL',
          placeholder: 'https://...',
          maxLength: 200,
        },
      ],
    },
    {
      id: 'tpl002',
      name: '图像分类模板v2',
      description: '图像分类增强版，新增难度评分与来源URL字段。',
      type: 'image_classification',
      fieldCount: 10,
      creator: 'o',
      createdAt: '2026-04-05T14:30:00Z',
      fields: [
        {
          id: 'f_title_1',
          type: 'title',
          fieldKey: '',
          label: '标注须知',
          description: '增强版分类模板，请仔细标注每个字段。',
          level: 4,
        },
        {
          id: 'f_category',
          type: 'radio',
          fieldKey: 'category',
          label: '图像类别',
          required: true,
          description: '选择图像中主要物体的类别',
          options: [
            { id: 'opt1', label: '猫', value: 'cat' },
            { id: 'opt2', label: '狗', value: 'dog' },
            { id: 'opt3', label: '鸟', value: 'bird' },
            { id: 'opt4', label: '其他', value: 'other' },
          ],
          direction: 'vertical',
        },
        {
          id: 'f_subcategory',
          type: 'select',
          fieldKey: 'subcategory',
          label: '子类别',
          placeholder: '请选择子类别',
          options: [
            { id: 'sc1', label: '波斯猫', value: 'persian' },
            { id: 'sc2', label: '橘猫', value: 'orange' },
            { id: 'sc3', label: '金毛', value: 'golden' },
            { id: 'sc4', label: '柯基', value: 'corgi' },
          ],
          searchable: true,
        },
        {
          id: 'f_tags',
          type: 'checkbox',
          fieldKey: 'tags',
          label: '附加标签',
          options: [
            { id: 'opt5', label: '室内', value: 'indoor' },
            { id: 'opt6', label: '室外', value: 'outdoor' },
            { id: 'opt7', label: '近景', value: 'closeup' },
            { id: 'opt8', label: '远景', value: 'distant' },
          ],
          direction: 'horizontal',
          maxCheck: 3,
        },
        {
          id: 'f_quality',
          type: 'select',
          fieldKey: 'quality',
          label: '图像质量',
          required: true,
          placeholder: '请选择质量等级',
          options: [
            { id: 'opt9', label: '高清', value: 'hd' },
            { id: 'opt10', label: '标准', value: 'sd' },
            { id: 'opt11', label: '模糊', value: 'blurry' },
          ],
          searchable: true,
        },
        {
          id: 'f_difficulty',
          type: 'rating',
          fieldKey: 'difficulty',
          label: '标注难度',
          description: '1=简单 5=极难',
          maxScore: 5,
          allowHalf: true,
          defaultValue: 3,
        },
        {
          id: 'f_isclear',
          type: 'switch',
          fieldKey: 'isClear',
          label: '目标是否清晰',
          defaultValue: false,
          checkedChildren: '清晰',
          unCheckedChildren: '模糊',
        },
        {
          id: 'f_note',
          type: 'textarea',
          fieldKey: 'note',
          label: '备注',
          placeholder: '补充说明（可选）',
          maxLength: 500,
          autoSize: true,
        },
        {
          id: 'f_url',
          type: 'input',
          fieldKey: 'sourceUrl',
          label: '数据来源URL',
          placeholder: 'https://...',
          maxLength: 200,
        },
        {
          id: 'f_color',
          type: 'input',
          fieldKey: 'dominantColor',
          label: '主色调',
          placeholder: '如：橙色、灰色',
          maxLength: 50,
        },
      ],
    },
    {
      id: 'tpl003',
      name: '目标检测模板v1',
      description: '基础目标检测模板，支持矩形框标注与类别选择。',
      type: 'object_detection',
      fieldCount: 5,
      creator: 'o',
      createdAt: '2026-03-15T10:20:00Z',
      fields: [
        {
          id: 'f_obj_type',
          type: 'select',
          fieldKey: 'objectType',
          label: '目标类别',
          required: true,
          placeholder: '请选择目标类别',
          options: [
            { id: 'o1', label: '行人', value: 'pedestrian' },
            { id: 'o2', label: '车辆', value: 'vehicle' },
            { id: 'o3', label: '自行车', value: 'bicycle' },
            { id: 'o4', label: '交通标志', value: 'sign' },
            { id: 'o5', label: '其他', value: 'other' },
          ],
          searchable: true,
        },
        {
          id: 'f_occlusion',
          type: 'radio',
          fieldKey: 'occlusion',
          label: '遮挡程度',
          required: true,
          options: [
            { id: 'oc1', label: '无遮挡', value: 'none' },
            { id: 'oc2', label: '轻微遮挡', value: 'light' },
            { id: 'oc3', label: '严重遮挡', value: 'heavy' },
          ],
          direction: 'horizontal',
        },
        {
          id: 'f_truncated',
          type: 'switch',
          fieldKey: 'isTruncated',
          label: '是否被截断',
          defaultValue: false,
          checkedChildren: '是',
          unCheckedChildren: '否',
        },
        {
          id: 'f_confidence',
          type: 'rating',
          fieldKey: 'confidence',
          label: '标注置信度',
          description: '对本次标注结果的确信程度',
          maxScore: 5,
          allowHalf: false,
        },
        {
          id: 'f_remark',
          type: 'textarea',
          fieldKey: 'remark',
          label: '补充说明',
          placeholder: '如有特殊情况请说明',
          maxLength: 300,
          autoSize: true,
        },
      ],
    },
    {
      id: 'tpl004',
      name: '目标检测模板v2',
      description: '目标检测增强版，新增遮挡率与截断判断字段。',
      type: 'object_detection',
      fieldCount: 7,
      creator: 'o',
      createdAt: '2026-04-12T08:15:00Z',
      fields: [
        {
          id: 'f_obj_type',
          type: 'select',
          fieldKey: 'objectType',
          label: '目标类别',
          required: true,
          placeholder: '请选择目标类别',
          options: [
            { id: 'o1', label: '行人', value: 'pedestrian' },
            { id: 'o2', label: '车辆', value: 'vehicle' },
            { id: 'o3', label: '自行车', value: 'bicycle' },
            { id: 'o4', label: '交通标志', value: 'sign' },
            { id: 'o5', label: '其他', value: 'other' },
          ],
          searchable: true,
        },
        {
          id: 'f_occlusion',
          type: 'radio',
          fieldKey: 'occlusion',
          label: '遮挡程度',
          required: true,
          options: [
            { id: 'oc1', label: '无遮挡', value: 'none' },
            { id: 'oc2', label: '轻微遮挡', value: 'light' },
            { id: 'oc3', label: '严重遮挡', value: 'heavy' },
          ],
          direction: 'horizontal',
        },
        {
          id: 'f_truncated',
          type: 'switch',
          fieldKey: 'isTruncated',
          label: '是否被截断',
          defaultValue: false,
          checkedChildren: '是',
          unCheckedChildren: '否',
        },
        {
          id: 'f_confidence',
          type: 'rating',
          fieldKey: 'confidence',
          label: '标注置信度',
          description: '对本次标注结果的确信程度',
          maxScore: 5,
          allowHalf: false,
        },
        {
          id: 'f_remark',
          type: 'textarea',
          fieldKey: 'remark',
          label: '补充说明',
          placeholder: '如有特殊情况请说明',
          maxLength: 300,
          autoSize: true,
        },
        {
          id: 'f_occlusion_rate',
          type: 'rating',
          fieldKey: 'occlusionRate',
          label: '遮挡率',
          description: '目标被遮挡的面积占比 1-5',
          maxScore: 5,
          allowHalf: true,
        },
        {
          id: 'f_lighting',
          type: 'radio',
          fieldKey: 'lighting',
          label: '光照条件',
          options: [
            { id: 'l1', label: '良好', value: 'good' },
            { id: 'l2', label: '一般', value: 'normal' },
            { id: 'l3', label: '昏暗', value: 'dark' },
          ],
          direction: 'horizontal',
        },
      ],
    },
    {
      id: 'tpl005',
      name: '语义分割模板v1',
      description: '适用于遥感、街景等像素级语义分割任务。',
      type: 'semantic_segmentation',
      fieldCount: 4,
      creator: 'o',
      createdAt: '2026-02-20T11:00:00Z',
      fields: [
        {
          id: 'f_seg_class',
          type: 'select',
          fieldKey: 'segClass',
          label: '分割类别',
          required: true,
          placeholder: '选择地物类别',
          options: [
            { id: 's1', label: '建筑', value: 'building' },
            { id: 's2', label: '植被', value: 'vegetation' },
            { id: 's3', label: '水体', value: 'water' },
            { id: 's4', label: '道路', value: 'road' },
            { id: 's5', label: '天空', value: 'sky' },
          ],
          searchable: true,
        },
        {
          id: 'f_boundary_q',
          type: 'radio',
          fieldKey: 'boundaryQuality',
          label: '边界质量',
          required: true,
          options: [
            { id: 'bq1', label: '清晰', value: 'clear' },
            { id: 'bq2', label: '模糊', value: 'blurry' },
            { id: 'bq3', label: '混合', value: 'mixed' },
          ],
          direction: 'horizontal',
        },
        {
          id: 'f_area_pct',
          type: 'rating',
          fieldKey: 'areaPercent',
          label: '区域占比',
          description: '该类别在图像中的面积占比 1-5',
          maxScore: 5,
          allowHalf: true,
        },
        {
          id: 'f_seg_note',
          type: 'textarea',
          fieldKey: 'segNote',
          label: '分割备注',
          placeholder: '特殊说明（如遮挡、混合区域）',
          maxLength: 300,
          autoSize: true,
        },
      ],
    },
    {
      id: 'tpl006',
      name: '语义分割模板v2',
      description: '语义分割增强版，新增区域备注与边界质量控制。',
      type: 'semantic_segmentation',
      fieldCount: 6,
      creator: 'o',
      createdAt: '2026-03-28T16:40:00Z',
      fields: [
        {
          id: 'f_seg_class',
          type: 'select',
          fieldKey: 'segClass',
          label: '分割类别',
          required: true,
          placeholder: '选择地物类别',
          options: [
            { id: 's1', label: '建筑', value: 'building' },
            { id: 's2', label: '植被', value: 'vegetation' },
            { id: 's3', label: '水体', value: 'water' },
            { id: 's4', label: '道路', value: 'road' },
            { id: 's5', label: '天空', value: 'other' },
          ],
          searchable: true,
        },
        {
          id: 'f_boundary_q',
          type: 'radio',
          fieldKey: 'boundaryQuality',
          label: '边界质量',
          required: true,
          options: [
            { id: 'bq1', label: '清晰', value: 'clear' },
            { id: 'bq2', label: '模糊', value: 'blurry' },
            { id: 'bq3', label: '混合', value: 'mixed' },
          ],
          direction: 'horizontal',
        },
        {
          id: 'f_area_pct',
          type: 'rating',
          fieldKey: 'areaPercent',
          label: '区域占比',
          description: '该类别在图像中的面积占比 1-5',
          maxScore: 5,
          allowHalf: true,
        },
        {
          id: 'f_seg_note',
          type: 'textarea',
          fieldKey: 'segNote',
          label: '分割备注',
          placeholder: '特殊说明（如遮挡、混合区域）',
          maxLength: 300,
          autoSize: true,
        },
        {
          id: 'f_cloud_cover',
          type: 'switch',
          fieldKey: 'cloudCover',
          label: '是否存在云遮挡',
          defaultValue: false,
          checkedChildren: '是',
          unCheckedChildren: '否',
        },
        {
          id: 'f_boundary_note',
          type: 'textarea',
          fieldKey: 'boundaryNote',
          label: '边界质量备注',
          placeholder: '如边界模糊请说明原因',
          maxLength: 200,
          autoSize: true,
        },
      ],
    },
    {
      id: 'tpl007',
      name: 'NER模板v1',
      description: '命名实体识别基础模板，覆盖人名、地名、机构名等实体类型。',
      type: 'text_ner',
      fieldCount: 3,
      creator: 'o',
      createdAt: '2026-01-18T09:30:00Z',
      fields: [
        {
          id: 'f_entity_type',
          type: 'select',
          fieldKey: 'entityType',
          label: '实体类型',
          required: true,
          placeholder: '选择实体类型',
          options: [
            { id: 'e1', label: '人名', value: 'person' },
            { id: 'e2', label: '地名', value: 'location' },
            { id: 'e3', label: '机构名', value: 'organization' },
            { id: 'e4', label: '日期', value: 'date' },
            { id: 'e5', label: '其他', value: 'other' },
          ],
          searchable: true,
        },
        {
          id: 'f_entity_text',
          type: 'input',
          fieldKey: 'entityText',
          label: '实体文本',
          required: true,
          placeholder: '输入识别到的实体文本',
          maxLength: 200,
        },
        {
          id: 'f_ner_note',
          type: 'textarea',
          fieldKey: 'nerNote',
          label: '标注备注',
          placeholder: '如有歧义请说明',
          maxLength: 300,
          autoSize: true,
        },
      ],
    },
    {
      id: 'tpl008',
      name: 'NER模板v2',
      description: 'NER增强版，支持实体关系标注与置信度评分。',
      type: 'text_ner',
      fieldCount: 5,
      creator: 'o',
      createdAt: '2026-02-25T13:20:00Z',
      fields: [
        {
          id: 'f_entity_type',
          type: 'select',
          fieldKey: 'entityType',
          label: '实体类型',
          required: true,
          placeholder: '选择实体类型',
          options: [
            { id: 'e1', label: '人名', value: 'person' },
            { id: 'e2', label: '地名', value: 'location' },
            { id: 'e3', label: '机构名', value: 'organization' },
            { id: 'e4', label: '日期', value: 'date' },
            { id: 'e5', label: '其他', value: 'other' },
          ],
          searchable: true,
        },
        {
          id: 'f_entity_text',
          type: 'input',
          fieldKey: 'entityText',
          label: '实体文本',
          required: true,
          placeholder: '输入识别到的实体文本',
          maxLength: 200,
        },
        {
          id: 'f_relation',
          type: 'select',
          fieldKey: 'relation',
          label: '实体关系',
          placeholder: '选择与其他实体的关系',
          options: [
            { id: 'r1', label: '属于', value: 'belongs_to' },
            { id: 'r2', label: '位于', value: 'located_in' },
            { id: 'r3', label: '相关', value: 'related_to' },
          ],
          searchable: true,
        },
        {
          id: 'f_ner_confidence',
          type: 'rating',
          fieldKey: 'nerConfidence',
          label: '标注置信度',
          description: '对实体识别的确信程度',
          maxScore: 5,
          allowHalf: false,
        },
        {
          id: 'f_ner_note',
          type: 'textarea',
          fieldKey: 'nerNote',
          label: '标注备注',
          placeholder: '如有歧义请说明',
          maxLength: 300,
          autoSize: true,
        },
      ],
    },
  ]);

  // 标注项。
  db.seed('annotation-items', [
    {
      id: 'd001',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/cat_001.jpg',
        fileName: 'cat_001.jpg',
        fileSize: '2.3MB',
        resolution: '1920x1080',
        description: '一只橘猫坐在窗台上晒太阳',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    {
      id: 'd002',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/dog_002.jpg',
        fileName: 'dog_002.jpg',
        fileSize: '3.1MB',
        resolution: '2048x1536',
        description: '一只金毛犬在草地上奔跑',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    {
      id: 'd003',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/bird_003.jpg',
        fileName: 'bird_003.jpg',
        fileSize: '1.8MB',
        resolution: '1600x1200',
        description: '一只麻雀停在树枝上',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    {
      id: 'd004',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/cat_dog_004.jpg',
        fileName: 'cat_dog_004.jpg',
        fileSize: '4.2MB',
        resolution: '2560x1440',
        description: '猫和狗同框，猫在左狗在右',
      },
      status: 'draft',
      annotationData: {
        category: 'cat',
        tags: ['indoor'],
        quality: 'hd',
        difficulty: 4,
        isClear: true,
        note: '猫占主要画面',
      },
      annotator: 'a',
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h001',
          operator: 'a',
          actionType: 'save_draft',
          fromStatus: 'pending',
          toStatus: 'draft',
          reason: null,
          timestamp: '2026-05-18T10:00:00Z',
        },
      ],
    },
    {
      id: 'd005',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/other_005.jpg',
        fileName: 'other_005.jpg',
        fileSize: '2.7MB',
        resolution: '1920x1080',
        description: '一辆汽车停在路边',
      },
      status: 'submitted',
      annotationData: {
        category: 'other',
        tags: ['outdoor', 'distant'],
        quality: 'sd',
        difficulty: 2,
        isClear: true,
        note: '',
      },
      annotator: 'a',
      submittedAt: '2026-05-18T14:30:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h002',
          operator: 'a',
          actionType: 'save_draft',
          fromStatus: 'pending',
          toStatus: 'draft',
          reason: null,
          timestamp: '2026-05-18T14:00:00Z',
        },
        {
          id: 'h003',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-18T14:30:00Z',
        },
      ],
    },
    {
      id: 'd006',
      taskId: 't006',
      rawData: {
        imageUrl: 'https://example.com/images/street_001.jpg',
        fileName: 'street_001.jpg',
        fileSize: '5.1MB',
        resolution: '3840x2160',
        description: '十字路口场景，包含行人和车辆',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    {
      id: 'd007',
      taskId: 't006',
      rawData: {
        imageUrl: 'https://example.com/images/street_002.jpg',
        fileName: 'street_002.jpg',
        fileSize: '4.8MB',
        resolution: '3840x2160',
        description: '人行横道上有行人通过',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    {
      id: 'd008',
      taskId: 't006',
      rawData: {
        imageUrl: 'https://example.com/images/street_003.jpg',
        fileName: 'street_003.jpg',
        fileSize: '3.9MB',
        resolution: '2560x1440',
        description: '雨天街道，视线较模糊',
      },
      status: 'draft',
      annotationData: {
        objectType: 'pedestrian',
        occlusion: 'light',
        isTruncated: false,
        confidence: 3,
        remark: '雨天拍摄，部分遮挡',
      },
      annotator: 'a',
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h004',
          operator: 'a',
          actionType: 'save_draft',
          fromStatus: 'pending',
          toStatus: 'draft',
          reason: null,
          timestamp: '2026-05-19T08:00:00Z',
        },
      ],
    },
    {
      id: 'd009',
      taskId: 't009',
      rawData: {
        imageUrl: 'https://example.com/images/crop_001.jpg',
        fileName: 'crop_001.jpg',
        fileSize: '2.1MB',
        resolution: '1920x1080',
        description: '水稻叶片出现褐色病斑',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    {
      id: 'd010',
      taskId: 't009',
      rawData: {
        imageUrl: 'https://example.com/images/crop_002.jpg',
        fileName: 'crop_002.jpg',
        fileSize: '1.9MB',
        resolution: '1600x1200',
        description: '健康的小麦植株，无病害迹象',
      },
      status: 'pending',
      annotationData: null,
      annotator: null,
      submittedAt: null,
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [],
    },
    // AI 已预审数据
    {
      id: 'd101',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/cat_101.jpg',
        fileName: 'cat_101.jpg',
        fileSize: '3.2MB',
        resolution: '2048x1536',
        description: '一只白色波斯猫趴在沙发上',
      },
      status: 'pending_review',
      annotationData: {
        category: 'cat',
        tags: ['indoor', 'closeup'],
        quality: 'hd',
        difficulty: 1,
        isClear: true,
        note: '目标清晰，室内近景',
      },
      annotator: 'a',
      submittedAt: '2026-05-19T09:15:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h005',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T09:15:00Z',
        },
        {
          id: 'h006',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T09:15:01Z',
        },
        {
          id: 'h007',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T09:15:05Z',
        },
        {
          id: 'h008',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T09:15:06Z',
        },
      ],
    },
    {
      id: 'd102',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/dog_102.jpg',
        fileName: 'dog_102.jpg',
        fileSize: '2.8MB',
        resolution: '1920x1080',
        description: '一只柯基犬在公园里玩耍',
      },
      status: 'pending_review',
      annotationData: {
        category: 'dog',
        tags: ['outdoor'],
        quality: 'hd',
        difficulty: 2,
        isClear: true,
        note: '',
      },
      annotator: 'a',
      submittedAt: '2026-05-19T10:30:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h009',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T10:30:00Z',
        },
        {
          id: 'h010',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T10:30:01Z',
        },
        {
          id: 'h011',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T10:30:05Z',
        },
        {
          id: 'h012',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T10:30:06Z',
        },
      ],
    },
    {
      id: 'd103',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/mixed_103.jpg',
        fileName: 'mixed_103.jpg',
        fileSize: '4.5MB',
        resolution: '2560x1440',
        description: '模糊图像，可能包含动物',
      },
      status: 'pending_review',
      annotationData: {
        category: 'cat',
        tags: ['outdoor', 'distant'],
        quality: 'blurry',
        difficulty: 5,
        isClear: false,
        note: '图像模糊难以判断',
      },
      annotator: 'a',
      submittedAt: '2026-05-19T11:45:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h013',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T11:45:00Z',
        },
        {
          id: 'h014',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T11:45:01Z',
        },
        {
          id: 'h015',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T11:45:05Z',
        },
        {
          id: 'h016',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T11:45:06Z',
        },
      ],
    },
    {
      id: 'd104',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/cat_104.jpg',
        fileName: 'cat_104.jpg',
        fileSize: '1.5MB',
        resolution: '1280x720',
        description: '一只黑猫的侧影，光线较暗',
      },
      status: 'pending_review',
      annotationData: {
        category: 'other',
        tags: ['indoor'],
        quality: 'blurry',
        difficulty: 4,
        isClear: false,
        note: '光线太暗看不清',
      },
      annotator: 'a',
      submittedAt: '2026-05-19T14:20:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h017',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T14:20:00Z',
        },
        {
          id: 'h018',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T14:20:01Z',
        },
        {
          id: 'h019',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T14:20:05Z',
        },
        {
          id: 'h020',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T14:20:06Z',
        },
      ],
    },
    {
      id: 'd105',
      taskId: 't006',
      rawData: {
        imageUrl: 'https://example.com/images/street_105.jpg',
        fileName: 'street_105.jpg',
        fileSize: '4.2MB',
        resolution: '2560x1440',
        description: '繁忙的十字路口，多辆汽车和行人',
      },
      status: 'pending_review',
      annotationData: {
        objectType: 'vehicle',
        occlusion: 'light',
        isTruncated: false,
        confidence: 4,
        remark: '多目标场景',
      },
      annotator: 'a',
      submittedAt: '2026-05-19T16:00:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h021',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T16:00:00Z',
        },
        {
          id: 'h022',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T16:00:01Z',
        },
        {
          id: 'h023',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T16:00:05Z',
        },
        {
          id: 'h024',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T16:00:06Z',
        },
      ],
    },
    {
      id: 'd106',
      taskId: 't006',
      rawData: {
        imageUrl: 'https://example.com/images/street_106.jpg',
        fileName: 'street_106.jpg',
        fileSize: '3.6MB',
        resolution: '1920x1080',
        description: '夜间街道，路灯下有行人 silhouette',
      },
      status: 'pending_review',
      annotationData: {
        objectType: 'pedestrian',
        occlusion: 'heavy',
        isTruncated: true,
        confidence: 2,
        remark: '夜间低光照，遮挡严重',
      },
      annotator: 'a',
      submittedAt: '2026-05-19T17:30:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h025',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T17:30:00Z',
        },
        {
          id: 'h026',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-19T17:30:01Z',
        },
        {
          id: 'h027',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T17:30:05Z',
        },
        {
          id: 'h028',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-19T17:30:06Z',
        },
      ],
    },
    {
      id: 'd107',
      taskId: 't006',
      rawData: {
        imageUrl: 'https://example.com/images/street_107.jpg',
        fileName: 'street_107.jpg',
        fileSize: '5.0MB',
        resolution: '3840x2160',
        description: '晴朗天气下的人行横道，行人和自行车',
      },
      status: 'pending_review',
      annotationData: {
        objectType: 'bicycle',
        occlusion: 'none',
        isTruncated: false,
        confidence: 5,
        remark: '',
      },
      annotator: 'a',
      submittedAt: '2026-05-20T08:00:00Z',
      reviewer: null,
      reviewedAt: null,
      rejectReason: null,
      auditHistory: [
        {
          id: 'h029',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-20T08:00:00Z',
        },
        {
          id: 'h030',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-20T08:00:01Z',
        },
        {
          id: 'h031',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-20T08:00:05Z',
        },
        {
          id: 'h032',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-20T08:00:06Z',
        },
      ],
    },
    // 已审核数据
    {
      id: 'd201',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/cat_201.jpg',
        fileName: 'cat_201.jpg',
        fileSize: '2.0MB',
        resolution: '1920x1080',
        description: '一只暹罗猫正对镜头',
      },
      status: 'reviewed',
      annotationData: {
        category: 'cat',
        tags: ['indoor', 'closeup'],
        quality: 'hd',
        difficulty: 1,
        isClear: true,
        note: '品种特征明显',
      },
      annotator: 'a',
      submittedAt: '2026-05-17T10:00:00Z',
      reviewer: 'r',
      reviewedAt: '2026-05-18T09:00:00Z',
      rejectReason: null,
      auditHistory: [
        {
          id: 'h033',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-17T10:00:00Z',
        },
        {
          id: 'h034',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-17T10:00:01Z',
        },
        {
          id: 'h035',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-17T10:00:05Z',
        },
        {
          id: 'h036',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-17T10:00:06Z',
        },
        {
          id: 'h037',
          operator: 'r',
          actionType: 'approve',
          fromStatus: 'pending_review',
          toStatus: 'reviewed',
          reason: null,
          timestamp: '2026-05-18T09:00:00Z',
        },
        {
          id: 'h037b',
          operator: 'r',
          actionType: 'archive',
          fromStatus: 'reviewed',
          toStatus: 'reviewed',
          reason: 'Review approved; automatically archived',
          timestamp: '2026-05-18T09:00:00Z',
        },
      ],
      archived: true,
      archivedAt: '2026-05-18T09:00:00Z',
    },
    {
      id: 'd202',
      taskId: 't001',
      rawData: {
        imageUrl: 'https://example.com/images/dog_202.jpg',
        fileName: 'dog_202.jpg',
        fileSize: '3.0MB',
        resolution: '2048x1536',
        description: '一只泰迪犬被错误标注为猫',
      },
      status: 'rejected',
      annotationData: {
        category: 'cat',
        tags: ['indoor'],
        quality: 'hd',
        difficulty: 2,
        isClear: true,
        note: '',
      },
      annotator: 'a',
      submittedAt: '2026-05-17T11:00:00Z',
      reviewer: 'r',
      reviewedAt: '2026-05-18T10:00:00Z',
      rejectReason: '类别标注错误：图像明显为犬类（泰迪），但标注为"猫"，请核实后重新标注。',
      auditHistory: [
        {
          id: 'h038',
          operator: 'a',
          actionType: 'submit',
          fromStatus: 'draft',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-17T11:00:00Z',
        },
        {
          id: 'h039',
          operator: '规则系统',
          actionType: 'ai_review_start',
          fromStatus: 'submitted',
          toStatus: 'submitted',
          reason: null,
          timestamp: '2026-05-17T11:00:01Z',
        },
        {
          id: 'h040',
          operator: '规则系统',
          actionType: 'ai_review_complete',
          fromStatus: 'submitted',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-17T11:00:05Z',
        },
        {
          id: 'h041',
          operator: '系统',
          actionType: 'assign_reviewer',
          fromStatus: 'pending_review',
          toStatus: 'pending_review',
          reason: null,
          timestamp: '2026-05-17T11:00:06Z',
        },
        {
          id: 'h042',
          operator: 'r',
          actionType: 'reject',
          fromStatus: 'pending_review',
          toStatus: 'rejected',
          reason: '类别标注错误：图像明显为犬类（泰迪），但标注为"猫"，请核实后重新标注。',
          timestamp: '2026-05-18T10:00:00Z',
        },
      ],
    },
  ]);

  // AI 预审结果。
  db.seed('reviews', [
    {
      id: 'ar101',
      dataItemId: 'd101',
      taskId: 't001',
      templateId: 'tpl001',
      reviewStatus: 'pass',
      score: 95,
      summary:
        '标注质量优秀，类别判断准确，标签完整，图像质量评估合理。白色波斯猫的类别特征明显，标注"猫"正确。',
      matchedRules: [],
      fieldWarnings: [
        {
          fieldKey: 'note',
          fieldLabel: '备注',
          message: '备注内容较简短，可补充更多细节',
          severity: 'info',
        },
      ],
      suggestions: [],
      reviewedAt: '2026-05-19T09:16:00Z',
      modelVersion: 'ai-review-v2.1',
    },
    {
      id: 'ar102',
      dataItemId: 'd102',
      taskId: 't001',
      templateId: 'tpl001',
      reviewStatus: 'pass',
      score: 82,
      summary: '标注基本正确，类别为"狗"无误。建议补充附加标签以提升标注丰富度。',
      matchedRules: [
        {
          ruleId: 'R003',
          name: '标签缺失检查',
          severity: 'info',
          description: '附加标签未选择任何项，建议至少选择一个场景标签',
        },
      ],
      fieldWarnings: [
        {
          fieldKey: 'tags',
          fieldLabel: '附加标签',
          message: '未选择任何附加标签，建议补充场景信息',
          value: [],
          severity: 'info',
        },
      ],
      suggestions: [
        {
          fieldKey: 'tags',
          fieldLabel: '附加标签',
          suggested: ['outdoor', 'closeup'],
          reason: '柯基犬在公园玩耍，属于室外近景场景',
        },
      ],
      reviewedAt: '2026-05-19T10:31:00Z',
      modelVersion: 'ai-review-v2.1',
    },
    {
      id: 'ar103',
      dataItemId: 'd103',
      taskId: 't001',
      templateId: 'tpl001',
      reviewStatus: 'risk',
      score: 52,
      summary:
        '标注存在多处问题：图像质量标注为"模糊"但难度评分为5（极难），且类别判断可疑。模糊图像的类别判定需要更谨慎。',
      matchedRules: [
        {
          ruleId: 'R001',
          name: '模糊图像类别置信度检查',
          severity: 'warning',
          description: '图像质量为"模糊"时，类别判定置信度应降低，建议标注员复核',
        },
        {
          ruleId: 'R005',
          name: '难度与质量一致性检查',
          severity: 'warning',
          description: '图像质量为"模糊"且难度为5分，可能存在标注困难，建议添加详细备注',
        },
      ],
      fieldWarnings: [
        {
          fieldKey: 'category',
          fieldLabel: '图像类别',
          message: '图像模糊时类别判断可能不可靠',
          value: 'cat',
          severity: 'warning',
        },
        {
          fieldKey: 'quality',
          fieldLabel: '图像质量',
          message: '图像质量为"模糊"',
          value: 'blurry',
          severity: 'warning',
        },
        {
          fieldKey: 'note',
          fieldLabel: '备注',
          message: '备注说明与类别判断矛盾',
          value: '图像模糊难以判断',
          severity: 'error',
        },
      ],
      suggestions: [
        {
          fieldKey: 'category',
          fieldLabel: '图像类别',
          current: 'cat',
          suggested: 'other',
          reason: '备注明确表示"难以判断"，建议类别改为"其他"',
        },
        {
          fieldKey: 'note',
          fieldLabel: '备注',
          current: '图像模糊难以判断',
          suggested: '图像模糊，疑似猫类但无法确认',
          reason: '备注应更详细',
        },
      ],
      reviewedAt: '2026-05-19T11:46:00Z',
      modelVersion: 'ai-review-v2.1',
    },
    {
      id: 'ar104',
      dataItemId: 'd104',
      taskId: 't001',
      templateId: 'tpl001',
      reviewStatus: 'fail',
      score: 35,
      summary: '标注存在严重问题：描述明确提到"黑猫"但类别标注为"其他"，与描述矛盾。',
      matchedRules: [
        {
          ruleId: 'R002',
          name: '类别与描述一致性检查',
          severity: 'error',
          description: '原始数据描述包含"猫"关键词，但标注类别为"其他"，存在明显矛盾',
        },
        {
          ruleId: 'R004',
          name: '必填字段合理性检查',
          severity: 'error',
          description: '目标清晰度标注为"模糊"，但描述中能辨认出猫的侧影',
        },
      ],
      fieldWarnings: [
        {
          fieldKey: 'category',
          fieldLabel: '图像类别',
          message: '描述为"黑猫侧影"但类别标注为"其他"',
          value: 'other',
          severity: 'error',
        },
        {
          fieldKey: 'isClear',
          fieldLabel: '目标是否清晰',
          message: '侧影仍可辨认目标',
          value: false,
          severity: 'warning',
        },
        {
          fieldKey: 'note',
          fieldLabel: '备注',
          message: '备注与描述矛盾',
          value: '光线太暗看不清',
          severity: 'error',
        },
      ],
      suggestions: [
        {
          fieldKey: 'category',
          fieldLabel: '图像类别',
          current: 'other',
          suggested: 'cat',
          reason: '原始描述明确提到"黑猫"',
        },
        {
          fieldKey: 'isClear',
          fieldLabel: '目标是否清晰',
          current: false,
          suggested: true,
          reason: '侧影仍可辨认目标',
        },
      ],
      reviewedAt: '2026-05-19T14:21:00Z',
      modelVersion: 'ai-review-v2.1',
    },
    {
      id: 'ar105',
      dataItemId: 'd105',
      taskId: 't006',
      templateId: 'tpl004',
      reviewStatus: 'pass',
      score: 88,
      summary: '目标检测标注质量良好，类别选择正确，遮挡程度评估合理。',
      matchedRules: [],
      fieldWarnings: [
        {
          fieldKey: 'remark',
          fieldLabel: '补充说明',
          message: '多目标场景建议补充目标数量等详细信息',
          value: '多目标场景',
          severity: 'info',
        },
      ],
      suggestions: [
        {
          fieldKey: 'remark',
          fieldLabel: '补充说明',
          current: '多目标场景',
          suggested: '多目标场景，包含3辆汽车和2名行人',
          reason: '建议注明具体目标数量',
        },
      ],
      reviewedAt: '2026-05-19T16:01:00Z',
      modelVersion: 'ai-review-v2.1',
    },
    {
      id: 'ar106',
      dataItemId: 'd106',
      taskId: 't006',
      templateId: 'tpl004',
      reviewStatus: 'risk',
      score: 45,
      summary: '标注存在风险：夜间低光照条件下的目标检测置信度低，遮挡程度为"严重"且目标被截断。',
      matchedRules: [
        {
          ruleId: 'R010',
          name: '低光照检测置信度检查',
          severity: 'warning',
          description: '夜间场景下目标检测置信度应谨慎评估',
        },
        {
          ruleId: 'R011',
          name: '遮挡与截断组合检查',
          severity: 'warning',
          description: '目标同时存在严重遮挡和截断',
        },
      ],
      fieldWarnings: [
        {
          fieldKey: 'occlusion',
          fieldLabel: '遮挡程度',
          message: '严重遮挡条件下标注可靠性较低',
          value: 'heavy',
          severity: 'warning',
        },
        {
          fieldKey: 'isTruncated',
          fieldLabel: '是否被截断',
          message: '目标被截断',
          value: true,
          severity: 'warning',
        },
        {
          fieldKey: 'confidence',
          fieldLabel: '标注置信度',
          message: '置信度仅为2/5',
          value: 2,
          severity: 'error',
        },
      ],
      suggestions: [
        {
          fieldKey: 'confidence',
          fieldLabel: '标注置信度',
          current: 2,
          suggested: 1,
          reason: '严重遮挡+截断+夜间场景，置信度应调整为1',
        },
      ],
      reviewedAt: '2026-05-19T17:31:00Z',
      modelVersion: 'ai-review-v2.1',
    },
    {
      id: 'ar107',
      dataItemId: 'd107',
      taskId: 't006',
      templateId: 'tpl004',
      reviewStatus: 'pass',
      score: 98,
      summary: '标注质量优秀。目标类别判断准确，无遮挡无截断，置信度5/5。',
      matchedRules: [],
      fieldWarnings: [],
      suggestions: [],
      reviewedAt: '2026-05-20T08:01:00Z',
      modelVersion: 'ai-review-v2.1',
    },
  ]);

  // 补齐旧标注项缺失的锁、版本和归档字段。
  const allItems = db.getAll('annotation-items');
  for (const item of allItems) {
    const patches = {};
    if (item.lockedBy === undefined) patches.lockedBy = null;
    if (item.lockedAt === undefined) patches.lockedAt = null;
    if (item.version === undefined) patches.version = 1;
    // archived / archivedAt：仅当字段未定义（undefined）时才初始化，
    // 已有值（包括 false / null）说明显式配置过，不再覆盖
    if (item.archived === undefined) {
      patches.archived = false;
      patches.archivedAt = null;
    }
    if (Object.keys(patches).length > 0) {
      db.updateById('annotation-items', item.id, patches);
    }
  }

  // 补齐旧任务缺失的归档字段。
  const allTasks = db.getAll('tasks');
  for (const task of allTasks) {
    if (task.archived === undefined) {
      db.updateById('tasks', task.id, { archived: false, archivedAt: null });
    }
  }
}); // end of transaction function definition

runSeed(); // execute the transaction

console.log('✅ Seed data populated successfully!');
console.log('   - users:      ', db.count('users'));
console.log('   - tasks:      ', db.count('tasks'));
console.log('   - templates:  ', db.count('templates'));
console.log('   - annotation-items:', db.count('annotation-items'));
console.log('   - reviews:    ', db.count('reviews'));
